[package]
name = "linkml_meta"
version = "0.0.0"
edition = "2021"

[lib]
name = "linkml_meta"
crate-type = ["lib"]

[dependencies]
pyo3 = { version = "0.25.0", features = ["chrono"]  , optional = true  }
serde = { version = "1.0", features = ["derive"]  , optional = true  }
serde-value = "0.7.0"
serde_yml = { version = "0.0.12", optional = true }
serde_path_to_error = { version = "0.1.17", optional = true }
pyo3-stub-gen = { version = "0.13.1", optional = true }
merge = "0.2.0"
chrono = { version = "0.4.41", features = ["serde"]  }


[features]
default = ["serde"]
pyo3 = ["dep:pyo3"]
serde = ["dep:serde", "dep:serde_yml", "dep:serde_path_to_error"]
stubgen = ["dep:pyo3-stub-gen", "pyo3"]
